---
title: "Plotting functions"
author: "Diego Diez"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, message=FALSE}
knitr::opts_chunk$set(fig.width=5, fig.height=5)
library(q3tools)
library(Biobase)
```


# Introduction

## Dots plot

You can use matrices.

```{r}
tmp1 <- data.matrix(iris[1:4, -5])
plotPoints(tmp1, group = rep(LETTERS[1:2], each = 2))
```

You can use other objects like `ExpressionSet`.

```{r}
data(sample.ExpressionSet)
tmp2 <- sample.ExpressionSet[1:4, ]
plotPoints(tmp2, group = tmp2$sex)
plotPoints(tmp2, group = tmp2$type)
```

## Histograms

A histogram.

```{r}
plotHistogram(tmp1)
plotHistogram(tmp1, group = rep(LETTERS[1:2], each = 2))
```
```{r}
plotHistogram(tmp2)
plotHistogram(tmp2, group = tmp2$sex)
plotHistogram(tmp2, group = tmp2$type)
```

## Heatmaps

A heatmap.

```{r}
tmp2 <- sample.ExpressionSet[1:25, ]
plotHeatmap(tmp2)
plotHeatmap(tmp2, col.cluster = TRUE, scale = TRUE)
```

A correlation heatmap.

```{r}
plotCorrelation(exprs(sample.ExpressionSet), cluster = TRUE)
```

## Venn diagrams

A venn diagram.

```{r}
plotVenn(
  iris[, -5] > 2,
  fill = c("cornflowerblue", "orange", "darkorchid1", "yellowgreen"),
  alpha = .3,
  col = NA
  )
```


## Gene tracks

A gene track.

```{r}
plotGene("Stat1", "mm10")
```

